org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx3g

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.welcome=never

kotlin.code.style=official

kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true

fleks.group=io.github.quillraven.fleks
fleks.version=2.16-SNAPSHOT
fleks.artifact=Fleks
